### ISSUE TITLE
Make spanstore interfaces asynchronous

### ISSUE THREAD

**Issue by anuraaga** [openzipkin/zipkin-java#111]
I have a use case for querying span stores in an asynchronous server and the blocking API makes me sad knowing most stores support full async.

In the note on BLOCK_ON_FUTURES, I noticed the decision on picking a future spec was punted but shall we get back to it?

Some options

1) RxJava Observable. In another issue I noticed people are already onboard with RxJava so this seems like the least controversial pick.

2) CompletableFuture. Forces span stores to Java8. There seems to be interest in keeping to Java7 for broader support but wonder whether there are actually use cases for slotting these into legacy code.

3) ListenableFuture. Requires Guava, which may be too large, though personally find working on pre-java8 code without it impossible. I took much advantage of ElasticSearch's dependency on it in my spanstore to preserve my sanity :)

4) Callback. Callbacks are gross, but lightest weight.

I like any of the non-callback solutions since converting between futures is easy :)

**Comment by adriancole** [comment]
>
> I have a use case for querying span stores in an asynchronous server and
> the blocking API makes me sad knowing most stores support full async.
>
well I wouldn't say most at the moment. JDBC isn't async, and in-memory is.
Cassandra indeed returns guava futures, though, and with ElasticSearch it
become a tie :).

> In the note on BLOCK_ON_FUTURES, I noticed the decision on picking a
> future spec was punted but shall we get back to it?
>
So block on futures is about the store use-case. I think your use case is
for query, particularly using the SpanStore api directly.

The most important thing we can do is itemize what the minimum goal is, as
there are so many things people mean when they say async. Ex. are you
looking to defer the result or compose it?

> 1) RxJava Observable. In another issue I noticed people are already
> onboard with RxJava so this seems like the least controversial pick.
>
agreed that this is the first that we spoke about. bear in mind that
there's some activity on 2.x, which is a sad reality the moment we start
choosing async composition libraries.

> 2) CompletableFuture. Forces span stores to Java8. There seems to be
> interest in keeping to Java7 for broader support but wonder whether there
> are actually use cases for slotting these into legacy code.
>
well it depends on what the async use case is. if it isn't a composition
one, regular future could work (even if not a happy one).

> 3) ListenableFuture. Requires Guava, which may be too large, though
> personally find working on pre-java8 code without it impossible. I took
> much advantage of ElasticSearch's dependency on it in my spanstore to
> preserve my sanity :)
>
There are indeed a family libraries that expose guava, but this like other
options are polarizing. Note that it is completely ok and possible to make
a GuavaSpanStore, which we could choose to expose as an option instead of a
requirement.

> 4) Callback. Callbacks are gross, but lightest weight.
>
callbacks, depending on what we do have one major advantage. They can
expose very specific things in the store use case, such as increment on
span stored vs rejected. For query, I kindof agree.

> I like any of the non-callback solutions since converting between futures
> is easy :)
>
First thought is to enumerate the use case you have, ex the framework
you're integrating with.

Kiting a bit.. GuavaSpanStore seems the path of least resistance as a
starting place as 2 span stores already use guava internally, and it is a
very popular library. This reduces adding a dependency that's only job is
to convert guava to rx.

We could test the model with cassandra and elasticsearch for example, and
make a blocking adapter for the synchronous api.

what say you?

**Comment by adriancole** [comment]
The TL; DR of my ramble is..

Let's say we move the 2 span stores that do async use guava internally
to a GuavaSpanStore...

By normalizing this part, we can avail async constructs without
imposing them on others. The internal code will look more coherent and
have a lower learning curve, as it doesn't require someone knowing
multiple async libraries.

If later we do Rx 1 or 2, well this step would be progress anyway, as
converting guava to rx is a relatively common feature. Also, this is
easy for folks in twitter land, too, as guava is easy to change to
twitter future.

**Comment by anuraaga** [comment]
>  and with ElasticSearch  it become a tie :).

I was thinking of potential (inevitable? ;) ) java ports of redis, mongodb, and hbase (opentsdb driver) too :)


Hey - to clarify I'm mostly interested in composition instead of just defering. More concretely, I would like to compose the result of a span store query into a netty Promise without any blocking. Of course I'm happy to use any future interface that supports listening. I'm also fine with a callback, since it's only slightly harder to convert to a listenable future than any of the other options.

Just to make sure I'm understanding your proposal right, it's something like this?
```java
public class ElasticsearchSpanStore implements SpanStore, GuavaSpanStore {
  @Override
  public List<Span> getTrace(long traceId) {
    return Futures.getUnchecked(getTraceAsync(traceId);
  }

  @Override
  public ListenableFuture<List<Span>> getTraceAsync(long traceId) {
    return toGuavaFuture(createElasticRequest(traceId).execute());
  }
}
```

and I guess we would stuff the GuavaSpanStore interface into a zipkin-guava-support module? 

Note, while Elasticsearch uses guava a lot, it doesn't actually extend ListenableFuture in its return value (I guess to decouple the API itself from guava). So the conversion step which I think you wanted to avoid by sticking with Guava would still exist - but when libraries expose their own custom Future this will be required regardless of which type of Future we decide to settle on. So picking ListenableFuture since one of our storage libraries exposes it directly and the other already depends on Guava seems reasonable to me. And FWIW, this approach looks like it would solve my use case just fine, and anyone who needs a composable asynchronous interface into these two span stores.

**Comment by adriancole** [comment]
>
> and with ElasticSearch it become a tie :).
>
> I was thinking of potential (inevitable? ;) ) java ports of redis,
> mongodb, and hbase (opentsdb driver) too :)
>
hah. well indeed there are rusting repos for each of those. depending on
volunteers they might be resurrected. It is nice to keep them in mind,
perhaps even inventory whatever the latest api each use and how or if they
deal with async composition. I'd treat this as low-priority, as without a
champion, span stores have no hope and shouldn't drive decisions. Ex
elasticsearch can work because of you, and a number of folks actively
asking about it.

> Hey - to clarify I'm mostly interested in composition instead of just
> defering. More concretely, I would like to compose the result of a span
> store query into a netty Promise without any blocking. Of course I'm happy
> to use any future interface that supports listening. I'm also fine with a
> callback, since it's only slightly harder to convert to a listenable future
> than any of the other options.
>
Cool. are you looking for the whole SpanStore api? ex to implement the http
interface of zipkin, or something custom, like just the queryrequest
method?


> Just to make sure I'm understanding your proposal right, it's something
> like this?
>
> public class ElasticsearchSpanStore implements SpanStore, GuavaSpanStore {
>   @Override
>   public List<Span> getTrace(long traceId) {
>     return Futures.getUnchecked(getTraceAsync(traceId);
>   }
>
>   @Override
>   public ListenableFuture<List<Span>> getTraceAsync(long traceId) {
>     return toGuavaFuture(createElasticRequest(traceId).execute());
>   }
> }
>
> I actually meant incompatible interfaces, ex varying only on result, but
this is an interesting idea. I was thinking that you can have
ElasticsearchSpanStore implement GuavaSpanStore, and then some dumb
blocking class that converts guava like GetUncheckedSpanStore implements
SpanStore has a GuavaSpanStore. Latter is easy to test, and would declutter
"guava native" spanstores from having double the method count.

and I guess we would stuff the GuavaSpanStore interface into a
> zipkin-guava-support module?
>
something like that... like spanstore-guava (assuming this is limited to
spanstore), or even an optional dependency on core (ex package the single
type and folks who don't use guava shouldn't load it)

> Note, while Elasticsearch uses guava a lot, it doesn't actually extend
> ListenableFuture in its return value (I guess to decouple the API itself
> from guava). So the conversion step which I think you wanted to avoid by
> sticking with Guava would still exist - but when libraries expose their own
> custom Future this will be required regardless of which type of Future we
> decide to settle on.
>
Oh interesting, yeah I assumed wrong on this. So it has a guava dependency,
and there's a base type called ListenableFuture, but it isn't compatible
with guava. This does have impact, as for example regardless of what we
choose, there's matters like callback executors with things like converting
to guava futures.

> So picking ListenableFuture since one of our storage libraries exposes it
> directly and the other already depends on Guava seems reasonable to me. And
> FWIW, this approach looks like it would solve my use case just fine, and
> anyone who needs a composable asynchronous interface into these two span
> stores.
>
TBH, I'm actually split now, but slightly in favor of guava vs rx.Single
for the context of this work. I think it is a combination of hesitation
about rx versions, the fact ES already has a guava dep, and similarity of
ES and guava listenable types that push me in that direction. I don't see
this as a generic async api, more an implementation-specific one that could
help us gain experience.

**Comment by anuraaga** [comment]
> Cool. are you looking for the whole SpanStore api? ex to implement the http interface of zipkin, or something custom, like just the queryrequest

Yep would like the whole API - for more detail I'm hoping to write an asynchronous zipkin-server based on armeria since I find tomcats to be scary. The API is so simple spring-mvc feels like overkill, and being fully asynchronous would probably allow HTTP to be fine in production without the mental cost of kafka.

Anyways, I first want to fork server for my own use, no plan on replacing the current zipkin-server (unless you're interested ;) ).

>  some dumb blocking class that converts guava
Ah duh makes sense, it would get boring writing the same Futues.getUnchecked in every single spanstore.

> TBH, I'm actually split now
I'm not really familiar with RxJava, but since it sounds like ListenableFuture may be reasonable and won't actually add dependencies in practice, I'd like to try it out. After ElasticsearchSpanStore is merged let me send a proposal PR if that sounds ok.

**Comment by adriancole** [comment]
Glad you are here. Looking forward to the pull request!
