### ISSUE TITLE
Return early on POST /spans

### ISSUE THREAD

**Issue by eirslett** [openzipkin/zipkin-java#133]
Some people might want to skip Kafka entirely, and make their applications send span data directly to zipkin-server over HTTP. (Maybe via a load balancer like haproxy)
In that case, any problems in zipkin-query would lead to slow HTTP responses, which in turn might affect the instrumented application.

What we need is a "spoon feeding" mechanism that lets instrumented applications get rid of their span data as quickly as possible, fire-and-forget. And then the spans will be fed into the storage backend at its maximum rate.

In zipkin-server, we could return HTTP 202 Accepted, and then add the received spans to an in-memory queue, which would be consumed by a SpanConsumer as quickly as possible. If the queue grows in size to more than some limit (e.g. 64 MB) we would start dropping spans.

The main benefit would be that you could run zipkin without kafka *or* scribe, just (multiple instances of) zipkin-server and the storage backend.

**Comment by adriancole** [comment]
Agreed.

This is why we have a span consumer interface (in fact I'd almost prefer
removing span consumption from SpanStore, except that it is convenient).

Ex. the below is an async span consumer used by the http endpoint, so that
we can return early. Ack that it is easy to miss the Async annotation,
which is what does the magic to make it return early.

https://github.com/openzipkin/zipkin-java/blob/master/zipkin-server/src/main/java/zipkin/server/ZipkinSpanWriter.java

**Comment by adriancole** [comment]
actually, we should be using AsyncSpanConsumer for this stuff..

**Comment by adriancole** [comment]
I have work in progress on this. It is definitely something to clarify prior to 1.0

**Comment by eirslett** [comment]
Ah, I see, I missed the magic annotation.

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-java/pull/136 removes the magic annotation, making async storage more explicit.

**Comment by adriancole** [comment]
<img width="1195" alt="screen shot 2016-05-07 at 8 21 19 pm" src="https://cloud.githubusercontent.com/assets/64215/15212832/a7edc96c-1875-11e6-85e6-5dbbc1f71ba5.png">

**Comment by eirslett** [comment]
:fireworks:
