### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by eirslett** [openzipkin/zipkin-java#165]
It would be nice to show the number of spans accepted by a zipkin server on the /metrics endpoint!

**Comment by adriancole** [comment]
I was waiting for someone to ask this :)

In [Brave](https://github.com/openzipkin/brave/pull/101), we defined below and copied the approach in Sleuth and also adopted it in [Sleuth](https://github.com/spring-cloud/spring-cloud-sleuth/issues/99) cc @pbetkier @kristofa @marcingrzejszczak

While some of the wording might need to be slightly revised, I'd love to reuse this and all the preceding work here. Ex. It is probably best to call it `SpanConsumerMetrics` or similar.

```java
/**
 * Monitor {@linkplain SpanCollector} by implementing reactions to these events, e.g. updating suitable metrics.
 *
 * See DropwizardMetricsScribeCollectorMetricsHandlerExample in isSampled sources for an example.
 */
public interface SpanCollectorMetricsHandler {

    /**
     * Called when spans are submitted to SpanCollector for processing.
     *
     * @param quantity the number of spans accepted.
     */
    void incrementAcceptedSpans(int quantity);

    /**
     * Called when spans become lost for any reason and won't be delivered to the target collector.
     *
     * @param quantity the number of spans dropped.
     */
    void incrementDroppedSpans(int quantity);

}
```

**Comment by adriancole** [comment]
One thing we might want to clarify for a collection sampler is the amount of spans dropped due to sampling. This came up in a chat with @anuraaga

In before-the-fact sampling (zipkin instrumentation default).. spans reported (spans accepted - dropped) is all post-sampling. When collection sampling is enabled, we'd only store a percentage of those reported. It might help to keep a counter that explains this.

One thing we could do is have "spans collected" being the count taken from the wire (before any collection-tier sampling). We could use "spans accepted" as the count sampled and "spans dropped" for those that couldn't be stored for any reason besides sampling.

**Comment by adriancole** [comment]
I've been thinking a while, and I think the following are most accessible and impactful

* `acceptedMessages` - count of messages received, which contain 0 or more spans. Ex POST requests or Kafka messages consumed.
* `droppedMessages` - count of messages that could not be read. Ex malformed content, or peer disconnect
  * `successfulMessages` - `= acceptedMessages - droppedMessages` is derived, so not reported. Alert when this is less than amount of messages sent from instrumentation.

* `acceptedSpans` - count of spans read from `successfulMessages`. When bundling is used, `acceptedSpans > successfulMessages`.
* `droppedSpans` - count of spans dropped for any reason. For example, failure queueing to storage or sampling decisions.
  * `storedSpans` - `<= acceptedSpans - droppedSpans` is derived, so not reported.  Alert when this drops below the collection-tier sample rate. Storage-specific alerts could improve such an alert, if they know which table or column should increment per span.

A span in the context of collection is <= span in the context of query. While it is advised that instrumentation report complete spans, Instrumentation often patch the same span twice, ex adding annotations. Also, RPC spans include at least 2 messages due to the client and the server reporting separately. Finally, some storage components merge patches at ingest. For these reasons, you should be cautious to alert on queryable spans vs `storedSpans`, unless you control the instrumentation in such a way that queryable spans/message is reliable.

**Comment by gena01** [comment]
is it possible to also partition the metrics based on incoming service/transport? I would love to see metrics showing HTTP vs Scribe vs Kafka

**Comment by adriancole** [comment]
>
> is it possible to also partition the metrics based on incoming
> service/transport? I would love to see metrics showing HTTP vs Scribe vs
> Kafka
>
Yep. the interface is decoupled from the partitioning/binding to metrics.

**Comment by eirslett** [comment]
We could use dropwizart metrics-core as a shared API for metrics? Then collector-cassandra-core would also need that dependency though. But as far as I can see, it doesn't have any transitive dependencies. https://github.com/dropwizard/metrics/blob/3.1-maintenance/metrics-core/pom.xml
@michaelsembwever WDYT?

**Comment by adriancole** [comment]
I don't want to add a core dependency on any metrics library. This would be
a polarizing move that would limit adoption, and negate the depedency-free
nature of the core library. Let's just bind metrics-core in the server for
now? It isn't much code

**Comment by adriancole** [comment]
ps just adding the interface now for early feedback while I implement it https://github.com/openzipkin/zipkin-java/pull/175

**Comment by adriancole** [comment]
noticed "spans accepted" clashes with accepting to storage. it is better as "spans read"

**Comment by adriancole** [comment]
also "messages accepted" seems worse than "messages received" especially in zipkin parlance

**Comment by adriancole** [comment]
incrementMessages, incrementDroppedMessages, incrementSpans, incrementDroppedSpans seem to work and dodge terms.

**Comment by adriancole** [comment]
ok WIP ready for a look. If looks good, I'll tidy for merge with tests, etc.

**Comment by adriancole** [comment]
I missed something. We need to record message size, too. This existed in zipkin-scala and will be very helpful for troubleshooting and configuring the transports #184
