### ISSUE TITLE
Maven or Gradle

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#4]
Since this project scope is only java, requires no special plugins, and will likely be authored by folks familiar with maven... should we just go ahead and do maven? Otherwise, if we do Gradle, which variant (nebula)?

**Comment by UncleBarney** [comment]
I think go ahead with maven would be a better idea since companies that are using java heavily probably already have mature tool chains build around maven.

**Comment by jen20** [comment]
:+1: for Maven - it will likely integrate better with most Java dev's workflow.

**Comment by spencergibb** [comment]
:+1: for maven.  We're going to start using [maven-wrapper](https://github.com/takari/maven-wrapper) for spring-cloud, similar to gradle-wrapper (a fork in fact).  That way there are no questions about what maven version works.

**Comment by 3thinkthendoit** [comment]
for Maven！

**Comment by llarsson** [comment]
:+1: for Maven, for the exact reason that @UncleBarney states.

**Comment by rtyler** [comment]
(Disclaimer: I'm a heavy Gradle user)

The benefit of Gradle is that there's definitely a huge variety of [plugins](http://plugins.gradle.org) actively being developed and supported, mostly because Gradle is so easy to extend.

For a *basic* Java project, I think both tools are going to largely be equivalent in terms of functionality provided and IDE integration. I would personally rather work with Groovy as a configuration language than XML, but that might just be me :)

**Comment by spencergibb** [comment]
@rtyler there's always https://github.com/takari/polyglot-maven, maven + groovy.

**Comment by adriancole** [comment]
maven wrapper it is! closed via #5
